#Name of the workflow
name: CI Pipeline

#start workflow on push event happens for branch main
#else every branch would trigger the workflow
on:
    push:
        branches:
            - main

jobs:
    hello: #job name
        #runs-on for type of runner github should provision for job
        runs-on: ubuntu-latest #selecting suitable machine

        #each jobs have work divided into steps(executed on the same runner)
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4

          - name: Setup Python
            run: actions/setup-python@v5
            with:
               python-version: "3.12"
            
          - name: Verify Python Version
            run: python --version

          - name: Install Dependencies
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
        
          - name: Verify Installed Packages
            run: pip list