#Name of the workflow
name: CI Pipeline

#start workflow on push event happens for branch main
#else every branch would trigger the workflow
on:
    push:
        branches:
            - main
    pull_request: #prevent broken codes from being merged
        branches:
            - main
jobs:
    backend_ci: #job name
        #runs-on for type of runner github should provision for job
        runs-on: ubuntu-latest #selecting suitable machine

        #each jobs have work divided into steps(executed on the same runner)
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4

          - name: Setup Python
            uses: actions/setup-python@v5
            with:
               python-version: "3.12"
               cache: "pip"
               cache-dependency-path: requirements-dev.txt

          # #cache dependecies to speed up
          # - name: Cache pip dependencies
          #   uses: actions/cache@v4
          #   with:
          #     path: ~/.cache/pip
          #     key: ${{ runner.os }}-pip-${{ hashFiles('requirements-dev.txt') }}
          #     restore-keys: |
          #       ${{ runner.os }}-pip-

          - name: Install Development Dependencies
            run: |
                python -m pip install --upgrade pip
                python -m pip install -r requirements-dev.txt
        
          - name: Run Ruff
            run: |
              ruff check .

          - name: Check Code Formatting
            run: |
              black --check .

          - name: Run Tests
            run: |
              python -m pytest -v